server:
  port: 8100
  ssl:
    enabled: true
    key-store: classpath:codesheepclient.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: client
spring:
  application:
    name: eureka-client
#注册中心
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: https://127.0.0.1:8000/eureka/
    registry-fetch-interval-seconds: 5
ssl:
  key-store: codesheepclient.p12
  key-store-password: 123456