server:
  port: 8000
  ssl:
    enabled: true
    #    证书路径
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-alias: server
    #    配置密码，就是在生成证书的时候输入的密码
    key-store-password: 123456

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
#    non-secure-port-enabled: false
#    secure-port-enabled: true
#    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://127.0.0.1:8000/eureka/
