server:
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:codesheepserver.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: server

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://127.0.0.1:8000/eureka/
